#!/bin/sh
PREFIX=/opt/kde
echo Preparing Directories ...
mkdir $PREFIX/share/apps/kmid
mkdir $PREFIX/share/apps/kmid/toolbar
echo Installing Binary...
cp kmid $PREFIX/bin/kmid
echo Installing Help...
cp kmid.html $PREFIX/share/doc/HTML/default/kmid.html
echo Installing Icon...
cp kmid.xpm $PREFIX/share/icons/kmid.xpm
echo Installing Toolbar Icons ...
cd toolbarxpm
cp *.xpm $PREFIX/share/apps/kmid/toolbar
cd ..
