/**********************************************************************

	--- Dlgedit generated file ---

	File: CDDBSetupData.cpp
	Last generated: Thu Jan 1 13:42:16 1998

	DO NOT EDIT!!!  This file will be automatically
	regenerated by dlgedit.  All changes will be lost.

 *********************************************************************/

#include "CDDBSetupData.h"

#define Inherited QWidget

#include <qgrpbox.h>
#include <qlabel.h>

CDDBSetupData::CDDBSetupData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name )
{
	QGroupBox* tmpQGroupBox;
	tmpQGroupBox = new QGroupBox( this, "GroupBox_1" );
	tmpQGroupBox->setGeometry( 10, 10, 365, 360 );
	tmpQGroupBox->setFrameStyle( 49 );
	tmpQGroupBox->setTitle( "" );
	tmpQGroupBox->setAlignment( 1 );

	QLabel* tmpQLabel;
	tmpQLabel = new QLabel( this, "Label_8" );
	tmpQLabel->setGeometry( 20, 55, 160, 20 );
	tmpQLabel->setText( "CDDB Base Directory" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	basedir_edit = new QLineEdit( this, "LineEdit_4" );
	basedir_edit->setGeometry( 20, 75, 340, 28 );
	basedir_edit->setText( "" );
	basedir_edit->setMaxLength( 32767 );
	basedir_edit->setEchoMode( QLineEdit::Normal );
	basedir_edit->setFrame( TRUE );

	tmpQLabel = new QLabel( this, "Label_9" );
	tmpQLabel->setGeometry( 20, 115, 210, 20 );
	tmpQLabel->setText( "Send CDDB submissions to:" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	submit_edit = new QLineEdit( this, "LineEdit_5" );
	submit_edit->setGeometry( 20, 135, 240, 28 );
	submit_edit->setText( "cddb-test@xmcd.com" );
	submit_edit->setMaxLength( 32767 );
	submit_edit->setEchoMode( QLineEdit::Normal );
	submit_edit->setFrame( TRUE );

	server_listbox = new QListBox( this, "ListBox_2" );
	server_listbox->setGeometry( 20, 225, 240, 135 );
	server_listbox->setFrameStyle( 51 );
	server_listbox->setLineWidth( 2 );
	server_listbox->insertItem( "cddb.cddb.com 888" );

	tmpQLabel = new QLabel( this, "Label_10" );
	tmpQLabel->setGeometry( 20, 175, 235, 20 );
	tmpQLabel->setText( "CDDB server" );
	tmpQLabel->setAlignment( 289 );
	tmpQLabel->setMargin( -1 );

	update_button = new QPushButton( this, "PushButton_7" );
	update_button->setGeometry( 270, 230, 90, 25 );
	update_button->setText( "Update" );
	update_button->setAutoRepeat( FALSE );
	update_button->setAutoResize( FALSE );

	current_server_label = new QLabel( this, "Label_4" );
	current_server_label->setGeometry( 20, 195, 240, 28 );
	current_server_label->setFrameStyle( 51 );
	current_server_label->setLineWidth( 2 );
	current_server_label->setText( "" );
	current_server_label->setAlignment( 289 );
	current_server_label->setMargin( -1 );

	remote_cddb_cb = new QCheckBox( this, "CheckBox_1" );
	remote_cddb_cb->setGeometry( 25, 20, 230, 30 );
	remote_cddb_cb->setText( "Enable Remote CDDB" );
	remote_cddb_cb->setAutoRepeat( FALSE );
	remote_cddb_cb->setAutoResize( FALSE );

	defaults_button = new QPushButton( this, "PushButton_2" );
	defaults_button->setGeometry( 270, 280, 90, 25 );
	defaults_button->setText( "Defaults" );
	defaults_button->setAutoRepeat( FALSE );
	defaults_button->setAutoResize( FALSE );

	help_button = new QPushButton( this, "PushButton_3" );
	help_button->setGeometry( 270, 335, 90, 25 );
	help_button->setText( "Help" );
	help_button->setAutoRepeat( FALSE );
	help_button->setAutoResize( FALSE );

	resize( 385, 420 );
}


CDDBSetupData::~CDDBSetupData()
{
}
